cmake_minimum_required(VERSION 3.20)

if(NOT DEFINED OUTPUT_FILE OR OUTPUT_FILE STREQUAL "")
    message(FATAL_ERROR "OUTPUT_FILE is required")
endif()

if(NOT DEFINED SOURCE_ROOT OR SOURCE_ROOT STREQUAL "")
    message(FATAL_ERROR "SOURCE_ROOT is required")
endif()

if(NOT DEFINED RESOURCE_FILES OR RESOURCE_FILES STREQUAL "")
    message(FATAL_ERROR "RESOURCE_FILES is required")
endif()

get_filename_component(OUTPUT_DIR "${OUTPUT_FILE}" DIRECTORY)
file(MAKE_DIRECTORY "${OUTPUT_DIR}")

set(GENERATED_CONTENT [=[/**
 * This file is generated by GenerateStdEmbedResourceTable.cmake.
 * Do not edit manually.
 */

#include "managers/StdEmbedResourceTable.hpp"

#include <array>
#include <cstddef>
#include <span>

namespace ui::managers
{
namespace
{

[[nodiscard]] std::span<const std::byte> MakeByteSpan(const unsigned char* data, std::size_t size)
{
    return std::as_bytes(std::span(data, size));
}

]=])

set(TABLE_ENTRIES "")
set(RESOURCE_INDEX 0)

foreach(LOGICAL_PATH IN LISTS RESOURCE_FILES)
    set(ABSOLUTE_PATH "${SOURCE_ROOT}/${LOGICAL_PATH}")
    if(NOT EXISTS "${ABSOLUTE_PATH}")
        message(FATAL_ERROR "Resource file does not exist: ${ABSOLUTE_PATH}")
    endif()

    file(READ "${ABSOLUTE_PATH}" RESOURCE_HEX HEX)
    string(LENGTH "${RESOURCE_HEX}" RESOURCE_HEX_LENGTH)
    math(EXPR RESOURCE_BYTE_COUNT "${RESOURCE_HEX_LENGTH} / 2")

    set(SYMBOL_NAME "STD_EMBED_RESOURCE_${RESOURCE_INDEX}")
    string(APPEND GENERATED_CONTENT "const unsigned char ${SYMBOL_NAME}[] = {\n")

    if(RESOURCE_BYTE_COUNT GREATER 0)
        math(EXPR LAST_BYTE_INDEX "${RESOURCE_BYTE_COUNT} - 1")
        set(CURRENT_LINE "    ")

        foreach(BYTE_INDEX RANGE ${LAST_BYTE_INDEX})
            math(EXPR HEX_OFFSET "${BYTE_INDEX} * 2")
            string(SUBSTRING "${RESOURCE_HEX}" ${HEX_OFFSET} 2 BYTE_HEX)
            string(APPEND CURRENT_LINE "0x${BYTE_HEX}")

            if(NOT BYTE_INDEX EQUAL LAST_BYTE_INDEX)
                string(APPEND CURRENT_LINE ", ")
            endif()

            math(EXPR BYTES_IN_LINE "(${BYTE_INDEX} + 1) % 12")
            if(BYTES_IN_LINE EQUAL 0)
                string(APPEND GENERATED_CONTENT "${CURRENT_LINE}\n")
                set(CURRENT_LINE "    ")
            endif()
        endforeach()

        if(NOT CURRENT_LINE STREQUAL "    ")
            string(APPEND GENERATED_CONTENT "${CURRENT_LINE}\n")
        endif()
    endif()

    string(APPEND GENERATED_CONTENT "};\n\n")
    string(APPEND TABLE_ENTRIES
        "    StdEmbedResourceEntry{std::string_view{\"${LOGICAL_PATH}\"}, MakeByteSpan(${SYMBOL_NAME}, sizeof(${SYMBOL_NAME}))},\n")
    math(EXPR RESOURCE_INDEX "${RESOURCE_INDEX} + 1")
endforeach()

string(APPEND GENERATED_CONTENT
    "const std::array<StdEmbedResourceEntry, ${RESOURCE_INDEX}> STD_EMBED_RESOURCE_TABLE{\n"
    "${TABLE_ENTRIES}"
    "};\n\n"
    "} // namespace\n\n"
    "std::span<const StdEmbedResourceEntry> GetStdEmbedResourceTable()\n"
    "{\n"
    "    return STD_EMBED_RESOURCE_TABLE;\n"
    "}\n\n"
    "const StdEmbedResourceEntry* FindStdEmbedResource(std::string_view logicalPath)\n"
    "{\n"
    "    for (const auto& entry : STD_EMBED_RESOURCE_TABLE)\n"
    "    {\n"
    "        if (entry.logicalPath == logicalPath)\n"
    "        {\n"
    "            return &entry;\n"
    "        }\n"
    "    }\n\n"
    "    return nullptr;\n"
    "}\n\n"
    "} // namespace ui::managers\n")

file(WRITE "${OUTPUT_FILE}" "${GENERATED_CONTENT}")