#这个文件是用来生成一个C++源文件的，该源文件包含一个资源表，资源表中的每个条目都包含一个逻辑路径和一个指向资源数据的字节跨度。资源数据以十六进制字符串的形式存储在输入文件中，并被转换为C++数组。

cmake_minimum_required(VERSION 3.20)

if(NOT DEFINED OUTPUT_FILE OR OUTPUT_FILE STREQUAL "")
    message(FATAL_ERROR "OUTPUT_FILE is required")
endif()

if(NOT DEFINED SOURCE_ROOT OR SOURCE_ROOT STREQUAL "")
    message(FATAL_ERROR "SOURCE_ROOT is required")
endif()

if(NOT DEFINED RESOURCE_FILES OR RESOURCE_FILES STREQUAL "")
    message(FATAL_ERROR "RESOURCE_FILES is required")
endif()

get_filename_component(OUTPUT_DIR "${OUTPUT_FILE}" DIRECTORY)
file(MAKE_DIRECTORY "${OUTPUT_DIR}")

set(STD_EMBED_CHUNK_BYTES 1024)

set(GENERATED_CONTENT [=[/**
 * This file is generated by GenerateStdEmbedResourceTable.cmake.
 * Do not edit manually.
 */

#include "managers/StdEmbedResourceTable.hpp"

#include <array>
#include <cstddef>
#include <span>

namespace ui::managers
{
namespace
{

[[nodiscard]] std::span<const std::byte> MakeByteSpan(const unsigned char* data, std::size_t size)
{
    return std::as_bytes(std::span(data, size));
}

]=])

set(TABLE_ENTRIES "")
set(RESOURCE_INDEX 0)

foreach(LOGICAL_PATH IN LISTS RESOURCE_FILES)
    set(ABSOLUTE_PATH "${SOURCE_ROOT}/${LOGICAL_PATH}")
    if(NOT EXISTS "${ABSOLUTE_PATH}")
        message(FATAL_ERROR "Resource file does not exist: ${ABSOLUTE_PATH}")
    endif()

    file(SIZE "${ABSOLUTE_PATH}" RESOURCE_BYTE_COUNT)

    set(SYMBOL_NAME "STD_EMBED_RESOURCE_${RESOURCE_INDEX}")
    string(APPEND GENERATED_CONTENT "const unsigned char ${SYMBOL_NAME}[] = {\n")

    if(RESOURCE_BYTE_COUNT GREATER 0)
        set(RESOURCE_OFFSET 0)
        while(RESOURCE_OFFSET LESS RESOURCE_BYTE_COUNT)
            file(READ "${ABSOLUTE_PATH}" RESOURCE_HEX_CHUNK OFFSET ${RESOURCE_OFFSET} LIMIT ${STD_EMBED_CHUNK_BYTES} HEX)
            if(NOT RESOURCE_HEX_CHUNK STREQUAL "")
                string(REGEX REPLACE "(..)" "0x\\1, " FORMATTED_CHUNK "${RESOURCE_HEX_CHUNK}")
                string(APPEND GENERATED_CONTENT "    ${FORMATTED_CHUNK}\n")
            endif()
            math(EXPR RESOURCE_OFFSET "${RESOURCE_OFFSET} + ${STD_EMBED_CHUNK_BYTES}")
        endwhile()
    endif()

    string(APPEND GENERATED_CONTENT "};\n\n")
    string(APPEND TABLE_ENTRIES
        "    StdEmbedResourceEntry{std::string_view{\"${LOGICAL_PATH}\"}, MakeByteSpan(${SYMBOL_NAME}, sizeof(${SYMBOL_NAME}))},\n")
    math(EXPR RESOURCE_INDEX "${RESOURCE_INDEX} + 1")
endforeach()

string(APPEND GENERATED_CONTENT
    "const std::array<StdEmbedResourceEntry, ${RESOURCE_INDEX}> STD_EMBED_RESOURCE_TABLE{\n"
    "${TABLE_ENTRIES}"
    "};\n\n"
    "} // namespace\n\n"
    "std::span<const StdEmbedResourceEntry> GetStdEmbedResourceTable()\n"
    "{\n"
    "    return STD_EMBED_RESOURCE_TABLE;\n"
    "}\n\n"
    "const StdEmbedResourceEntry* FindStdEmbedResource(std::string_view logicalPath)\n"
    "{\n"
    "    for (const auto& entry : STD_EMBED_RESOURCE_TABLE)\n"
    "    {\n"
    "        if (entry.logicalPath == logicalPath)\n"
    "        {\n"
    "            return &entry;\n"
    "        }\n"
    "    }\n\n"
    "    return nullptr;\n"
    "}\n\n"
    "} // namespace ui::managers\n")

file(WRITE "${OUTPUT_FILE}" "${GENERATED_CONTENT}")